USE [Menace]

DROP TABLE Player
DROP TABLE Game
DROP TABLE Turn
DROP TABLE GameHistory
DROP TABLE Bead
DROP TABLE Matchbox
DROP TABLE BoardPosition
DROP TABLE AIMenace
DROP TABLE AIOptimalMove
DROP TABLE AIRandomMove
GO
